version: "2"

services:

  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ESWORKSHOP_USERNAME: esworkshop
      ESWORKSHOP_PASSWORD: password123
    volumes:
      - ./setup/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"