#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE esworkshop;
    CREATE USER $ESWORKSHOP_USERNAME WITH PASSWORD '$ESWORKSHOP_PASSWORD';
    GRANT ALL privileges ON DATABASE esworkshop to $ESWORKSHOP_USERNAME;
EOSQL
